// ====================================
// UI.JS - Rendering & Display
// ====================================

/**
 * Render all UI elements
 */
function renderUI() {
  updateI18nText();
  updateMeters();
  updateRoundDisplay();
  renderActions();
}

/**
 * Update all meter displays
 */
function updateMeters() {
  const metrics = ['safety', 'infrastructure', 'morale'];
  metrics.forEach(metric => {
    const value = clamp(gameState.metrics[metric], 0, 100);
    document.getElementById(`${metric}Value`).textContent = roundValue(value);
    document.getElementById(`${metric}Meter`).style.width = value + '%';
  });

  // Resource Points (not a percentage)
  const rpValue = gameState.metrics.resourcePoints;
  document.getElementById('resourceValue').textContent = roundValue(rpValue);
  const rpPercent = Math.min(100, (rpValue / 100) * 100);
  document.getElementById('resourceMeter').style.width = rpPercent + '%';
}

/**
 * Update round counter display
 */
function updateRoundDisplay() {
  document.getElementById('roundDisplay').textContent = gameState.currentDay;
}

/**
 * Render action buttons dynamically
 */
function renderActions() {
  const actionsGrid = document.getElementById('actionsGrid');
  actionsGrid.innerHTML = '';

  // Only display actionPool - never show all actions
  // actionPool is generated by generateActionPool() in drawNextEvent()
  const actionsToDisplay = gameState.actionPool && gameState.actionPool.length > 0 
    ? gameState.actionPool 
    : []; // Empty array until actionPool is generated

  actionsToDisplay.forEach(action => {
    const btn = document.createElement('button');
    btn.className = 'action-btn';
    
    // Build action effects HTML
    let effectsHTML = '<div class="action-effects">';
    Object.entries(action.effects).forEach(([metric, value]) => {
      if (value !== 0) {
        const isPositive = value > 0;
        const icon = isPositive ? '↑' : '↓';
        const className = isPositive ? 'effect-positive' : 'effect-negative';
        
        // Format metric name
        let metricLabel = metric.charAt(0).toUpperCase() + metric.slice(1);
        if (metric === 'resourcePoints') metricLabel = 'RP';
        
        effectsHTML += `
          <span class="effect-item ${className}">
            ${metricLabel} ${icon}${Math.abs(value)}
          </span>
        `;
      }
    });
    effectsHTML += '</div>';
    
    btn.innerHTML = `
      <div class="action-btn-title">${action.title[gameState.currentLanguage]}</div>
      <div class="action-btn-description">${action.description ? action.description[gameState.currentLanguage] : ''}</div>
      ${effectsHTML}
    `;

    btn.addEventListener('click', () => {
      // Check if player has enough resources (cost is negative resourcePoints effect)
      const cost = Math.abs(action.effects.resourcePoints || 0);
      if (cost > gameState.metrics.resourcePoints) {
        const lang = gameState.currentLanguage;
        const message = lang === 'en' 
          ? `Not enough Resource Points! Need ${cost}, have ${roundValue(gameState.metrics.resourcePoints)}.`
          : `Không đủ Điểm Tài Nguyên! Cần ${cost}, có ${roundValue(gameState.metrics.resourcePoints)}.`;
        alert(message);
        return;
      }

      executeAction(action);
    });

    actionsGrid.appendChild(btn);
  });
}

/**
 * Display event card
 */
function displayEvent() {
  const event = gameState.currentEvent;
  const lang = gameState.currentLanguage;

  document.getElementById('eventTitle').textContent = event.title[lang];
  document.getElementById('eventDescription').textContent = event.description[lang];

  // Display effects as badges
  const effectsEl = document.getElementById('eventEffects');
  effectsEl.innerHTML = '';

  Object.entries(event.effects).forEach(([metric, value]) => {
    if (value !== 0) {
      const badge = document.createElement('div');
      badge.className = `effect-badge ${value > 0 ? 'positive' : 'negative'}`;
      badge.textContent = `${metric}: ${value > 0 ? '+' : ''}${value}`;
      effectsEl.appendChild(badge);
    }
  });
}

/**
 * Show flood safety tip
 */
function showTip() {
  const event = gameState.currentEvent;
  const lang = gameState.currentLanguage;

  const tipText = document.getElementById('tipText');
  tipText.textContent = event.tip[lang];

  openModal('tipModal');
}

/**
 * Open modal dialog
 */
function openModal(modalId) {
  const modal = document.getElementById(modalId);
  modal.classList.add('active');
}

/**
 * Close modal dialog
 */
function closeModal(modalId) {
  const modal = document.getElementById(modalId);
  modal.classList.remove('active');
}

/**
 * Close modals when clicking outside
 */
document.addEventListener('click', (e) => {
  const modals = document.querySelectorAll('.modal');
  modals.forEach(modal => {
    if (e.target === modal) {
      modal.classList.remove('active');
    }
  });
});
